- name: Take variables from course file
  hosts: local
  connection: local
  vars_files: 
  - course.yaml  
  tasks: 
  - name: print course details 
    ansible.builtin.debug:
      msg: "Course Details: {{ Course }}, {{ Duration }}. {{ Trainer }}" 