- name: variables through prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username 
    prompt: what is your name?
    private: false

  - name: password
    prompt: What is your password?
    private: false 
    
  tasks:    
  - name: print credentials
    ansible.builtin.debug:   
      msg: "Credentials: username: {{ username }}, password: {{ password }}"