- name: variables through inventory
  hosts: local
  connection: local
  tasks:
  - name: print course details
    ansible.builtin.debug:
      msg: "Course details: Course: {{ Course }}, Duration: {{ Duration }}, Trainer: {{ Trainer }}"