- name: print names in loop
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}" #item is reservered 
    loop: #people in funny family under 40 years
    - giri
    - siri
    - balaji
    - charan
    - mithun
    - mehira
    - dharwik
    - dhanvish
    - teja
    - sasi