- name: install multiple packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Install multiple packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
      - nginx
      - nodejs
      - zip
    