- name: check user present or not
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: checking whether user present or not 
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true

  - name: print user_output
    ansible.builtin.debug:
      msg: "{{ user_output }}"